---
- name: update /etc/default/locale for Debian family
  when: 'ansible_os_family == "Debian"'
  become: yes
  block:
    - name: run update-locale
      command: 'update-locale {{locale_LC_ALL}} {{locale_LANG}}'

    - name: check /etc/default/locale
      command: cat /etc/default/locale
      register: cat_locale
      failed_when: item not in cat_locale.stdout
      loop:
        - "{{locale_LC_ALL}}"
        - "{{locale_LANG}}"

- name: update /etc/locale.conf for RedHat family
  when: 'ansible_os_family == "RedHat"'
  become: yes
  block:

    - name: add LANG in /etc/locale.conf
      lineinfile:
        path: /etc/locale.conf
        regexp: '^LANG='
        line: '{{locale_LANG}}'
        create: yes

    - name: check /etc/locale.conf for LANG
      command: cat /etc/locale.conf
      register: cat_locale
      failed_when: item not in cat_locale.stdout
      loop:
        # LC_ALL is not valid in /etc/locale.conf
        # - "{{locale_LC_ALL}}"
        - "{{locale_LANG}}"

- name: udpate /etc/environment for LC_ALL
  become: yes
  lineinfile:
    path: /etc/environment
    regexp: '^LC_ALL='
    line: '{{locale_LC_ALL}}'
    create: yes

- name: udpate /etc/environment for LANG
  become: yes
  lineinfile:
    path: /etc/environment
    regexp: '^LANG='
    line: '{{locale_LANG}}'
    create: yes

- command: cat /etc/environment
