---

- name: gather facts
  tags: always
  setup:

- name: show current locale
  command: locale
  register: locale

# if not enabled, try to enable it
- name: setup locale if not enabled
  when: locale_LC_ALL not in locale.stdout
  block:

    - debug:
        msg: "locale {{ locale_name }} not enabled by default, try to enable"

    - name: check all available locales round 1
      command: locale --all-locales
      register: locales1

    - name: install locale if not available
      include_tasks: install.yml
      when: locale_name not in locales1.stdout

    - name: check all available locales round 2
      command: locale --all-locales
      register: locales2

    # if still not available, generate it ourselves
    - name: generate locale if still not available
      when: locale_name not in locales2.stdout
      become: yes
      command: >
        localedef
        --charmap {{locale_charmap}}
        --inputfile {{locale_inputfile}}
        --no-archive
        {{locale_name}}

    - name: check all available locales round 3
      command: locale --all-locales
      register: locales3

    # if still not available, we fail
    - name: failed if still not available
      when: locale_name not in locales3.stdout
      fail:
        msg: "fail to gen locale {{locale_name}}"

    - name: enable locale
      include_tasks: enable.yml
